***Numpy Fundamentals***

>1. Creating Numpy Array

In [ ]:
import numpy as np

lst = [10,20,30,40,50]
arr = np.array([1,2,3,4,5])
print(lst, type(lst))
print(arr, type (arr))

>2. Creating Basic Arrays

In [ ]:
# 1D array -> Vectors
a = np.array([1,2,3,4])
print(a)

# 2D array -> Metrix
b = np.array([ [1,2,3,4] ])
print(b)

# 3D array -> Tensors
c = np.array([ [[10,20, 30, 40], [30,40,50,60]] ])
print(c)


>3. Specifying data types of numpy array

In [ ]:
# Creating floating arrays
a = np.array([10,20,30,40], dtype=float)
print(a, a.dtype)

# Creating Boolean arrays
b = np.array([0, 10, -10, 90, 66, 10.6], dtype=bool)
print(b, b.dtype)

>4. Array Initialization Functions

In [ ]:
# 1) np.arange()
a  = np.arange(1,10)   # last value is exclusive
print(a)

b  = np.arange(2,21, 2)   # -> even  number of np array
print(b)

# 2) np.ones
ones_array = np.ones( (3,2) )
print(ones_array)
print()

# 3) np.zeros
zeros_array = np.zeros( (3,2) )
print(zeros_array)

# 4) np.random
random_array = np.random.random( (3,2) )  # generates num b/w 0 and 1
print(random_array, 1)

# 5) linspace
l = np.linspace(1,5, 10)
print(l)

# 6) Identity metrix
i = np.identity(3)
print(i)

# 💡 Note -> In case of ones, zeros & random we pass tuple

>5. Memory optimization

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print(a, a.dtype)

a.astype('int16')    #  64 -> 32, 16, 8

>6. Creating metrix and tensors using arange + reshape()

   

In [ ]:
# Creating a 2D array ->  metrix
a = np.arange(1,11).reshape(5,2)
print(a)

In [ ]:
# Creating a 3D array -> Tensors
a = np.arange(1,13).reshape(3,2,2)
print(a)

In [ ]:
a = np.array([1,2,3,4,5], dtype='int16')
print(a, a.dtype)

>7. Numpy Array Attributes

In [ ]:
# 1) ndim -> It runs the dimentions of an array.

# Vector
A1 = np.arange(1,11)
print(A1, '->', A1.ndim)

# Metrix
A2 = np.arange(1,13).reshape(3,4)
print(A2, '->', A2.ndim)

# Tensor
A3 = np.arange(1,19).reshape(3,2,3)
print(A3, '->', A3.ndim)

In [ ]:
# 3) shape --> It simply returns a tuple which specifies the total number of elements

# Vector
A1 = np.arange(1,11)
print(A1, '->', A1.shape)

# Metrix
A2 = np.arange(1,13).reshape(3,4)
print(A2, '->', A2.shape)

# Tensor
A3 = np.arange(1,19).reshape(3,2,3)
print(A3, '->', A3.shape)

In [ ]:
# 4) size  -> It returns the total number of element in array.

# Vector
A1 = np.arange(1,11)
print(A1, '->', A1.size)

# Metrix
A2 = np.arange(1,13).reshape(3,4)
print(A2, '->', A2.size)

# Tensor
A3 = np.arange(1,19).reshape(3,2,3)
print(A3, '->', A3.size)

In [ ]:
# 5) Item size  --> it returns the size of  individual elements of an array in bytes 

# Vector
A1 = np.arange(1,11)  # dtype -> int 64 by default
print(A1, '->', A1.itemsize)

# Metrix
A2 = np.arange(1,13, dtype='int32').reshape(3,4)
print(A2, '->', A2.itemsize)

# Tensor
A3 = np.arange(1,19, dtype='int16').reshape(3,2,3)
print(A3, '->', A3.itemsize)

In [ ]:
# 6) dtype  --> it tells the data type of an array

# Vector
A1 = np.arange(1,11) 
print(A1, '->', A1.dtype)

# Metrix
A2 = np.arange(1,13, dtype='int32').reshape(3,4)
print(A2, '->', A2.dtype)

# Tensor
A3 = np.arange(1,19, dtype='int16').reshape(3,2,3)
print(A3, '->', A3.dtype)

>8. Array Operation - ( Scalar & Vector )

In [ ]:
# 1. Scalar Operations:

# Arithmetic --> + , - , *, / , //, %, ** 
m = np.arange(1,13).reshape(3,4)
print(m,'\n')
result = m + 2
print(result) 

# Relational --> > , < , >=, <= , ==, != 
r = np.arange(1,13).reshape(3,4)
print(r,'\n')
result = r > 9
print(result) 

In [ ]:
# 2. Vector Operations.
a1 = np.arange(1,16).reshape(3,5)
print(a1)
print('\n')

a2 = np.arange(10,25).reshape(3,5)
print(a2)
print('\n')

res = a1 + a2
print(res)


>9. Array Functions:


In [ ]:
# max, min, sum, prod
a = np.arange(1,21).reshape(5,4)
print(a)
print(f'Max = {np.max(a)}') 
print(f'Min = {np.min(a)}') 
print(f'Sum = {np.sum(a)}') 
print(f'Prod = {np.prod(a)}') 

In [ ]:
# Axis Parameter
a = np.arange(1,21).reshape(5,4)
print(a)
print(f'Max of each rows = {np.max(a, axis=1)}')
print(f'Min of each column = {np.min(a, axis=0)}')
print(f'Sum of each row = {np.sum(a, axis=1)}')

In [ ]:
# Statistical Functions
b = np.arange(10,30).reshape(5,4)
print(b)
print(f'Mean = {np.mean(b)}')
print(f'Median = {np.median(b)}')
print(f'Standard Deviation = {np.std(b)}')
print(f'Variance = {np.var(b)}')

In [ ]:
# Dot product
a1 = np.arange(1,13).reshape(3,4)
print(a1)
print()

a2 = np.arange(0,12).reshape(4,3)
print(a2)
print()

result = np.dot(a1,a2)
print(result)

In [ ]:
# log and exponent 

a = np.arange(10,30).reshape(5,4)
print(a) 
print() 

log_metrix = np.log(a)
print(log_metrix)
print()

exp_metrix = np.exp(a)
print(exp_metrix)
print()

In [ ]:
# round, floor, ceil
b = np.random.random((5,5))*100
print(b) 
print() 
print( np.round(b)) 

>10. Indexing
- Positive indexing
- Negative indexing

In [ ]:
# 1) Vector Indexing
a = np.array([10,20, 30, 40, 50, 60])
print(a)

print(f"First element: {a[0]}")    # -> positive indexing   
print(f"Last element: {a[-1]}")    # -> negative indexing

In [ ]:
# 2) Metrix Indexing
b = np.arange(1,13).reshape(4,3)
print(b)

# print -> 1, 5, 9, 11, 6
print(b[0][0]) 
print(b[1][1]) 
print(b[2][2]) 
print(b[3][1]) 
print(b[1][2]) 

In [ ]:
# 3) Tensors Indexing
c = np.arange(1,31).reshape(2,5,3)
print(c)

# print -> 1, 10, 12, 9, 16, 21, 28, 30, 23, 17
print(c[0][0][0])
print(c[0][3][0])
print(c[0][3][2])
print(c[0][2][2])
print(c[1][0][0])
print(c[1][1][2])
print(c[1][4][2])
print(c[1][2][1])
print(c[1][0][1])

>11. Slicing

In [ ]:
# 1) Slicing vectors
a = np.arange(10)
print(a)

#  Slice -> 0, [1,2,3], [7,8,9], [1,3,5,7], [2,4,6,8], [3,6] 
print( a[0:1] )
print( a[1:4] )
print( a[-3:] )
print( a[1:8:2] )
print( a[2:9:2] )
print( a[3:7:3] )

In [ ]:
# 2) Slicing Metrix
b = np.arange(12).reshape(3,4)
print(b)
print()

# slice -> 1st row
print (b[0, ::] )

# slice -> 3rd row
print (b[2, ::] )

# slice -> 2nd column
print (b[::, 2] )

In [ ]:
# Slicing sub metrix:
''' Questions:
  i) [ 5 6 ]              
     [ 9 10 ]

  ii) [ 6 7 ]
      [ 10 11] 

  iii) [ 2 3 ]
       [ 6 7] 

   iv) [ 4 5 ]
       [ 8 9 ] 

   v) [ 2 3 ]
      [ 10 11 ] 

   vi)  [ 0 3 ]
        [ 8 11 ] 
'''  
m = np.arange(12).reshape(3,4)
print(m)
print()

# i)
print( m[1: ,1:3 ] )
print()

# ii)
print( m[1: ,2:4 ] )
print()

# iii)
print( m[:2 ,2: ] )
print()

# iv)
print( m[1: , :2 ] )
print()

# v)
print( m[::2 , 2:] )
print()

# vi)
print( m[::2 , ::3] )
print()

# vii) [1,3,9,11]
print( m[::2 , 1::2] )
print()

In [ ]:
# 3) Slicing Tensors
c = np.arange(27).reshape(3,3,3)
print(c)
print()

# print("1. slicing 1st 2d array ")
# print(c[0])
# print()

# print("2. slicing 1st and last 2d array ")
# print( c[0::2] )
# print()

# print("3. 2nd row of  2d array ")
# print( c[0, 1, :] )
# print()

# print("4. 2nd column of 2nd 2d array ")
# print( c[1, :, 1] )
# print()

# print("5. 2nd [22,23,25,26] sub matrix ")
# print( c[2, 1:, 1:] )
# print()

# print("6. 2nd [0,2,18,20] sub matrix ")
# print( c[::2, 0, ::2 ] )
# print()


# print("7. center element of metrix -> 13 ")
# print( c[1,1,1] )
# print()

# print("8. First row of every layer ")
# print( c[:,0,:] )
# print()

# print("8. four corner elements of the last layer[18, 20, 24, 26] ")
# print( c[2, ::2, ::2] )
# print()

print("9. Reverses the order of the layers but keeps the rows and columns in their original order")
print( c[::-1, :, : :] )
print()

>12. Iteration on numpy array

In [ ]:
# 1) Iteration on vectors
a = np.arange(10)

for e in a:
  print(e, end=' ')

In [ ]:
# 2) Iteration on matrix
a = np.arange(12).reshape(4,3)

for e in a:
  print(e)

In [ ]:
# 3) Iteration on tensors
a = np.arange(18).reshape(3,3,2)

for e in a:
  print(e)

>13. Advance iteration on numpy array -> nditer()

In [ ]:
# Iteration on tensors
a = np.arange(18).reshape(3,3,2)

for e in np.nditer(a):
  print(e, end=' ')


>14. Transpose of array

In [ ]:
m = np.arange(12).reshape(4,3)
print(m)
print()

# print(np.transpose(m))
print(m.T)

>15. Flattening Arrays

In [ ]:
a = np.arange(24).reshape(2,4,3)
print(a)
print()

print(np.ravel(a))

>16. Numpy Stacking

In [ ]:
# Horizontal Stacking
a1 = np.arange(12).reshape(3,4)
print(a1)
print()

a2 = np.arange(15,27).reshape(3,4)
print(a2)
print()

h_stack = np.hstack((a1, a2, a1))
print(h_stack)

In [ ]:
# Vertical Stacking
a1 = np.arange(12).reshape(3,4)
print(a1)
print()

a2 = np.arange(15,27).reshape(3,4)
print(a2)
print()

h_stack = np.vstack((a1, a2))
print(h_stack)

>17. Splitting

In [ ]:
# Horizontal split
a = np.arange(12).reshape(3,4)
print(a)
print()

print(np.hsplit(a, 2))

In [185]:
# vertical split
a = np.arange(12).reshape(4,3)
print(a)
print()

print(np.vsplit(a, 2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]
