In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [6]:
v = np.arange(10) * np.nan
v[4] = 1
print(v)

[nan nan nan nan  1. nan nan nan nan nan]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a, b = int(input('a = ')), int(input('a = '))
arr = np.random.random((a,b)) * 10

print(arr) 
print(np.mean(arr)) 

[[7.03137637 1.28115832 6.11782823 5.64635735]
 [1.10260427 1.19548139 3.03136283 1.39330963]
 [5.24483018 9.43683865 9.9937809  4.59971264]]
4.672886729634588


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
a = 4
b = 4
def parametar(a:int, b:int):
  arr = np.ones( (a,b), dtype='int16' )
  arr[ 1:3, 1:3 ] = 0
  print(arr)

parametar(a,b)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [20]:
a = np.random.random(10)
print(a)

[0.47874203 0.48405795 0.7143492  0.90989053 0.54463569 0.10890311
 0.70902308 0.0589474  0.04273613 0.90315375]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [26]:
# a = np.zeros( (3,4), dtype='int16' )
# a[0][0],  a[1][1],  a[2][2] = 1,1,1
# print(a)

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [62]:
# m = np.linspace(0,4,25, dtype='int16').reshape(5,5)
m = np.random.random((5,5))*5
print(m.astype('int'))

[[0 0 2 2 4]
 [0 4 0 0 1]
 [2 2 0 0 3]
 [1 1 1 2 3]
 [3 2 1 4 3]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [70]:
v = np.random.random( (10,2) ) * 100
print(v.astype('int8')) 

[[41  3]
 [26 88]
 [84 23]
 [86 51]
 [ 5 38]
 [70 62]
 [26 90]
 [43  3]
 [26 75]
 [63 98]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
t = np.arange(336).reshape(6,7,8)
# print(t)
print(t[1,5,4])

100


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [84]:
arr = np.array( [int(e) for e in input('Enter space seperated numbers: ').split(' ')] )
print(arr)
result =  arr.astype('float')
print(result[::-1])

[  1   2   3   4   5  -8 -10]
[-10.  -8.   5.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [93]:
a = np.array([])
b = np.array([1,2])

print(np.size(a))
print(np.size(b))

0
2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [104]:
def softmax(array):
  pass

arr = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])

if np.ndim(arr) == 1:
  softmax(arr)
else:
  print('Array must be 1-d')

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [167]:
def vstacking(*t):
  for i in range(len(t)):
    if not isinstance( t[i], np.ndarray ):
      print("ERROR: You can't pass a list.")
      return
   
  result =  np.vstack((t))
  return result




a = [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]]

b = [[1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1]]

c= [ [0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
     [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]]

l = [1,23,4,5,]

a1 = np.array(a)
a2 = np.array(b)
a3 = np.array(c)

print(vstacking(a1,a2, a3)) 

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2026-03-12`. The end date should be included and for simplicity, choose dates from a same year.



In [ ]:
def date_array(date_1:str, date_2:str):
  pass

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [168]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [169]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [170]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [171]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [172]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [173]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1926, 3438, 8700, 1428, 6509],
       [5491, 3710, 6253, 5758, 6565],
       [4057,   84, 2198, 8193, 9677],
       [5731, 9456, 7615, 5459, 4299],
       [ 746, 2509,  236, 5528, 4858],
       [3944, 5185, 9300, 7184, 9767],
       [ 862, 6228, 9724, 2880, 9801],
       [1946, 8014, 6434, 7482, 2683]], dtype=int32)

In [174]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [230]:
def third_largest(array:np.ndarray, n:int) -> int:

  if n > np.size(array):
    print("n can not be greater than length of array. ")

    exit
  elif not isinstance(array, np.ndarray):
    print("You must pass an numpy array ")
    exit
  
  else:
    temp_list = []
    temp_array = np.array([])
    temp_array = array
    i = 1
    while i<=n:
      max = (np.max(temp_array))
      temp_list.append(max)
      max_index = np.where( temp_array == max )
      
      new_arr = np.delete(temp_array, max_index)
      temp_array = new_arr
      i += 1
  return  temp_list[n-1]


b1 = np.array([12,34,40,7,1,0])
b2 = np.array([12,34,40,7,1,0])
l = [1,2]

result = third_largest(b1, 3)
print(result)

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [241]:
a = np.array([1,2,3]) 
print(a)
np.repeat(a, 3)

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3])